services:
  - type: web
    runtime: php
    name: url-shortener
    repo: https://github.com/brayanibp/URLShortener.git # Default: Repo containing render.yaml
    numInstances: 1   # Manual scaling configuration. Default: 1 for new services
    region: oregon # Default: oregon
    plan: free    # Default: starter
    branch: main      # Default: master
    buildCommand: composer install
    preDeployCommand: php artisan migrate
    startCommand: php artisan serve
    autoDeploy: true # Disable automatic deploys
    maxShutdownDelaySeconds: 120 # Increase graceful shutdown period. Default: 30, Max: 300
    envVars: # Environment variables
      - key: DATABASE_URL
        fromDatabase: # Reference a property of a database (see available properties below)
          name: mydatabase
          property: connectionString

  # A web service that builds from a Dockerfile
  - type: web
    runtime: docker
    name: webdis
    repo: https://github.com/render-examples/webdis.git # Default: Repo containing render.yaml
    rootDir: webdis # Default: Repo root
    plan: free
    dockerCommand: ./webdis.sh # Default: Dockerfile CMD
    healthCheckPath: /
    envVars:
      - key: REDIS_HOST
        fromService: # Reference a property from another service (see available properties below)
          type: redis
          name: lightning
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: lightning
          property: port

databases:
  - name: url-shortener
    databaseName: url_shortener
    user: url-shortener
    ipAllowList: []
    plan: free
