services:
  - type: web
    runtime: docker
    dockerContext: . # current directory
    dockerfilePath: Dockerfile # PHP NGINX IMAGE
    name: url-shortener
    repo: https://github.com/brayanibp/URLShortener.git # Default: Repo containing render.yaml
    numInstances: 1   # Manual scaling configuration. Default: 1 for new services
    region: oregon # Default: oregon
    plan: free    # Default: starter
    branch: main      # Default: master
    autoDeploy: true # Disable automatic deploys
    envVars: # Environment variables
      - key: APP_KEY
        sync: false
      - key: DB_SHARD_ID
        value: 1
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: url-shortener
          property: host
      - key: DB_PORT
        fromDatabase:
          name: url-shortener
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: url-shortener
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: url-shortener
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: url-shortener
          property: password
      - key: CACHE_STORE
        value: redis
      - key: REDIS_HOST
        fromService: # Reference a property from another service (see available properties below)
          type: redis
          name: lightning
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: lightning
          property: port

  # A web service that builds from a Dockerfile
  - type: redis
    name: lightning
    ipAllowList: []
    plan: free # Default: starter
    maxmemoryPolicy: noeviction # Default: allkeys-lru

databases:
  - name: url-shortener
    databaseName: url_shortener
    user: urlshortener
    ipAllowList: []
    plan: free
