services:
  - type: web
    runtime: docker
    dockerfilePath: Dockerfile # PHP NGINX IMAGE
    dockerContext: ./
    dockerCommand: ./start.sh
    name: url-shortener
    repo: https://github.com/brayanibp/URLShortener.git # Default: Repo containing render.yaml
    numInstances: 1   # Manual scaling configuration. Default: 1 for new services
    region: oregon # Default: oregon
    plan: free    # Default: starter
    branch: main      # Default: master
    autoDeploy: true # Disable automatic deploys
    envVars: # Environment variables
      - key: DATABASE_URL
        fromDatabase: # Reference a property of a database (see available properties below)
          name: mydatabase
          property: connectionString
      - key: REDIS_HOST
        fromService: # Reference a property from another service (see available properties below)
          type: redis
          name: lightning
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: lightning
          property: port

  # A web service that builds from a Dockerfile
  - type: redis
    name: lightning
    ipAllowList: []
    plan: free # Default: starter
    maxmemoryPolicy: noeviction # Default: allkeys-lru

databases:
  - name: url-shortener
    databaseName: url_shortener
    user: urlshortener
    ipAllowList: []
    plan: free
